In [1]:
import pandas as pd

In [46]:
df = pd.read_csv("IMDB-Movie-Dataset(2023-1951).csv")

df

,Unnamed: 0,movie_id,movie_name,year,genre,overview,director,cast
0,0,tt15354916,Jawan,2023,"Action, Thriller",A high-octane action thriller which outlines t...,Atlee,"Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ..."
1,1,tt15748830,Jaane Jaan,2023,"Crime, Drama, Mystery",A single mother and her daughter who commit a ...,Sujoy Ghosh,"Kareena Kapoor, Jaideep Ahlawat, Vijay Varma, ..."
2,2,tt11663228,Jailer,2023,"Action, Comedy, Crime",A retired jailer goes on a manhunt to find his...,Nelson Dilipkumar,"Rajinikanth, Mohanlal, Shivarajkumar, Jackie S..."
3,3,tt14993250,Rocky Aur Rani Kii Prem Kahaani,2023,"Comedy, Drama, Family",Flamboyant Punjabi Rocky and intellectual Beng...,Karan Johar,"Ranveer Singh, Alia Bhatt, Dharmendra, Shabana..."
4,4,tt15732324,OMG 2,2023,"Comedy, Drama",An unhappy civilian asks the court to mandate ...,Amit Rai,"Pankaj Tripathi, Akshay Kumar, Yami Gautam, Pa..."
...,...,...,...,...,...,...,...,...
2194,2195,tt11112474,Heeriye,NaN,Thriller,Add a Plot,Subhash Ghai,"Shatrughan Sinha, Reena Roy, Ajit Khan, Premna..."
2195,2196,tt0332766,Sur: The Melody of Life,2002,"Drama, Musical, Romance",A renowned music teacher mentors a promising y...,Tanuja Chandra,"Lucky Ali, Simone Singh, Achint Kaur, Ehsan Khan"
2196,2197,tt8622232,Time to Dance,2021,"Musical, Romance",When a ballroom dancer's shot at a crucial tou...,Stanley D'Costa,"Sooraj Pancholi, Isabelle Kaif, Waluscha D'Sou..."
2197,2198,tt0187351,Nigahen: Nagina Part II,1989,"Drama, Family, Fantasy",After the tragic deaths of his son Ajit and da...,Harmesh Malhotra,"Sunny Deol, Sridevi, Anupam Kher, Gulshan Grover"
2198,2199,tt0297241,Kyo Kii... Main Jhuth Nahin Bolta,2001,"Action, Comedy, Drama",Raj is a successful lawyer due to constant che...,David Dhawan,"Govinda, Sushmita Sen, Rambha, Anupam Kher"

In [3]:
df.head()

,Unnamed: 0,movie_id,movie_name,year,genre,overview,director,cast
0,0,tt15354916,Jawan,2023,"Action, Thriller",A high-octane action thriller which outlines t...,Atlee,"Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ..."
1,1,tt15748830,Jaane Jaan,2023,"Crime, Drama, Mystery",A single mother and her daughter who commit a ...,Sujoy Ghosh,"Kareena Kapoor, Jaideep Ahlawat, Vijay Varma, ..."
2,2,tt11663228,Jailer,2023,"Action, Comedy, Crime",A retired jailer goes on a manhunt to find his...,Nelson Dilipkumar,"Rajinikanth, Mohanlal, Shivarajkumar, Jackie S..."
3,3,tt14993250,Rocky Aur Rani Kii Prem Kahaani,2023,"Comedy, Drama, Family",Flamboyant Punjabi Rocky and intellectual Beng...,Karan Johar,"Ranveer Singh, Alia Bhatt, Dharmendra, Shabana..."
4,4,tt15732324,OMG 2,2023,"Comedy, Drama",An unhappy civilian asks the court to mandate ...,Amit Rai,"Pankaj Tripathi, Akshay Kumar, Yami Gautam, Pa..."

In [4]:
df.tail()

,Unnamed: 0,movie_id,movie_name,year,genre,overview,director,cast
2194,2195,tt11112474,Heeriye,NaN,Thriller,Add a Plot,Subhash Ghai,"Shatrughan Sinha, Reena Roy, Ajit Khan, Premna..."
2195,2196,tt0332766,Sur: The Melody of Life,2002,"Drama, Musical, Romance",A renowned music teacher mentors a promising y...,Tanuja Chandra,"Lucky Ali, Simone Singh, Achint Kaur, Ehsan Khan"
2196,2197,tt8622232,Time to Dance,2021,"Musical, Romance",When a ballroom dancer's shot at a crucial tou...,Stanley D'Costa,"Sooraj Pancholi, Isabelle Kaif, Waluscha D'Sou..."
2197,2198,tt0187351,Nigahen: Nagina Part II,1989,"Drama, Family, Fantasy",After the tragic deaths of his son Ajit and da...,Harmesh Malhotra,"Sunny Deol, Sridevi, Anupam Kher, Gulshan Grover"
2198,2199,tt0297241,Kyo Kii... Main Jhuth Nahin Bolta,2001,"Action, Comedy, Drama",Raj is a successful lawyer due to constant che...,David Dhawan,"Govinda, Sushmita Sen, Rambha, Anupam Kher"

In [5]:
df.tail(3)

,Unnamed: 0,movie_id,movie_name,year,genre,overview,director,cast
2196,2197,tt8622232,Time to Dance,2021,"Musical, Romance",When a ballroom dancer's shot at a crucial tou...,Stanley D'Costa,"Sooraj Pancholi, Isabelle Kaif, Waluscha D'Sou..."
2197,2198,tt0187351,Nigahen: Nagina Part II,1989,"Drama, Family, Fantasy",After the tragic deaths of his son Ajit and da...,Harmesh Malhotra,"Sunny Deol, Sridevi, Anupam Kher, Gulshan Grover"
2198,2199,tt0297241,Kyo Kii... Main Jhuth Nahin Bolta,2001,"Action, Comedy, Drama",Raj is a successful lawyer due to constant che...,David Dhawan,"Govinda, Sushmita Sen, Rambha, Anupam Kher"

In [7]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [9]:
df.columns

Index(['Unnamed: 0', 'movie_id', 'movie_name', 'year', 'genre', 'overview',
       'director', 'cast'],
      dtype='object')

In [10]:
print(df["genre"])

0              Action, Thriller
1         Crime, Drama, Mystery
2         Action, Comedy, Crime
3         Comedy, Drama, Family
4                 Comedy, Drama
                 ...
2194                   Thriller
2195    Drama, Musical, Romance
2196           Musical, Romance
2197     Drama, Family, Fantasy
2198      Action, Comedy, Drama
Name: genre, Length: 2199, dtype: object

In [12]:
type(df.columns)

pandas.core.indexes.base.Index

In [14]:
list(df.columns)

['Unnamed: 0',
 'movie_id',
 'movie_name',
 'year',
 'genre',
 'overview',
 'director',
 'cast']

In [15]:
df["movie_name"]

0                                   Jawan
1                              Jaane Jaan
2                                  Jailer
3         Rocky Aur Rani Kii Prem Kahaani
4                                   OMG 2
                      ...
2194                              Heeriye
2195              Sur: The Melody of Life
2196                        Time to Dance
2197              Nigahen: Nagina Part II
2198    Kyo Kii... Main Jhuth Nahin Bolta
Name: movie_name, Length: 2199, dtype: object

In [16]:
type(df["movie_name"])

pandas.core.series.Series

In [22]:
df[['genre','movie_id']].head(3)

                   genre    movie_id
0       Action, Thriller  tt15354916
1  Crime, Drama, Mystery  tt15748830
2  Action, Comedy, Crime  tt11663228

In [23]:
df.dtypes

Unnamed: 0     int64
movie_id      object
movie_name    object
year          object
genre         object
overview      object
director      object
cast          object
dtype: object

In [24]:
df.columns

Index(['Unnamed: 0', 'movie_id', 'movie_name', 'year', 'genre', 'overview',
       'director', 'cast'],
      dtype='object')

In [2]:
import pandas as pd

In [4]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [5]:
df1 = pd.read_excel("Excel-Practice-Data-for-Pivot-Table-1.xlsx")
df1

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Excel Data Entry Practice Exercises PDF,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Date,Client,Region,Month,Year,Quarter,Amount
3,NaN,2019-07-15 00:00:00,ABC Corporation,South,July,2019,Q3,1741089
4,NaN,2019-07-19 00:00:00,Bridges Company,East,July,2019,Q3,514989
...,...,...,...,...,...,...,...,...
712,NaN,2022-10-25 00:00:00,Titan Industries,South,October,2022,Q4,50000
713,NaN,2022-10-27 00:00:00,Titan Industries,East,October,2022,Q4,720000
714,NaN,2022-10-27 00:00:00,Titan Industries,North,October,2022,Q4,70000
715,NaN,2022-10-29 00:00:00,ABC Corporation,North,October,2022,Q4,50500
716,NaN,2022-10-30 00:00:00,Chiral Corporation,North,October,2022,Q4,63900

In [6]:
df1.head(3)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Excel Data Entry Practice Exercises PDF,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Date,Client,Region,Month,Year,Quarter,Amount

In [8]:
df1.tail()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
712,NaN,2022-10-25 00:00:00,Titan Industries,South,October,2022,Q4,50000
713,NaN,2022-10-27 00:00:00,Titan Industries,East,October,2022,Q4,720000
714,NaN,2022-10-27 00:00:00,Titan Industries,North,October,2022,Q4,70000
715,NaN,2022-10-29 00:00:00,ABC Corporation,North,October,2022,Q4,50500
716,NaN,2022-10-30 00:00:00,Chiral Corporation,North,October,2022,Q4,63900

In [10]:
df1.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7'],
      dtype='object')

In [15]:
df1.dtypes

Unnamed: 0    float64
Unnamed: 1     object
Unnamed: 2     object
Unnamed: 3     object
Unnamed: 4     object
Unnamed: 5     object
Unnamed: 6     object
Unnamed: 7     object
dtype: object

In [18]:
df1["Unnamed: 0"]

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
712   NaN
713   NaN
714   NaN
715   NaN
716   NaN
Name: Unnamed: 0, Length: 717, dtype: float64

In [20]:
pip install lxml

Collecting lxml
  Downloading lxml-6.1.1-cp310-cp310-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-6.1.1-cp310-cp310-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 17.5 MB/s eta 0:00:01
   ---------- ----------------------------- 1.0/4.0 MB 7.2 MB/s eta 0:00:01
   -------------------- ------------------- 2.1/4.0 MB 4.9 MB/s eta 0:00:01
   ------------------------------- -------- 3.1/4.0 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 4.2 MB/s  0:00:01
Installing collected packages: lxml
Successfully installed lxml-6.1.1
Note: you may need to restart the kernel to use updated packages.

In [25]:
import requests

In [37]:
import requests

# 1. URL set karein
url = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"

# 2. Fake browser identity (Headers) banayein taaki Wikipedia hame block na kare
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
}

# 3. Pehle requests library se web page ka access lein
response = requests.get(url, headers=headers)

# 4. Ab Pandas ko bolein ki us HTML text me se table nikaale
tables = pd.read_html(response.text)

tables

C:\Users\kshit\AppData\Local\Temp\ipykernel_21720\310200763.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

[                                Location  Population % of world         Date  \
 0                                  World  8232000000       100%  13 Jun 2025
 1                                  India  1417492000      17.2%   1 Jul 2025
 2                                  China  1404890000      17.0%  31 Dec 2025
 3                          United States   341784857       4.1%   1 Jul 2025
 4                              Indonesia   288315089       3.5%  31 Dec 2025
 ..                                   ...         ...        ...          ...
 235         Christmas Island (Australia)        1692         0%   1 Jan 2021
 236                   Niue (New Zealand)        1681         0%  11 Nov 2022
 237                         Vatican City         882         0%  31 Dec 2024
 238  Cocos (Keeling) Islands (Australia)         593         0%  30 Jun 2020
 239                Pitcairn Islands (UK)          35         0%   1 Jul 2023

     Source (official or from the United Nations) Notes
 0                            UN projection[1][3]   NaN
 1                         Official projection[4]   [b]
 2                           Official estimate[5]   [c]
 3                           Official estimate[6]   [d]
 4                  National annual projection[7]   NaN
 ..                                           ...   ...
 235                             2021 Census[248]   NaN
 236                             2022 Census[249]   NaN
 237                         Official figure[250]  [ah]
 238                             2021 Census[251]   NaN
 239                       Official estimate[252]   NaN

 [240 rows x 6 columns],
      vteLists of countries by population statistics  \
 0                                            Global
 1                             Continents/subregions
 2                                  Intercontinental
 3                                Cities/urban areas
 4                                   Past and future
 5                                Population density
 6                                 Growth indicators
 7                                   Life expectancy
 8                                Other demographics
 9                                            Health
 10                         Education and innovation
 11                                         Economic
 12  List of international rankings Lists by country

      vteLists of countries by population statistics.1
 0   Current population United Nations Demographics...
 1   Africa Antarctica Asia Europe North America Ca...
 2   Americas Arab world Commonwealth of Nations Eu...
 3   World cities National capitals Megacities Mega...
 4   Past and future population Estimates of histor...
 5   Current density Past and future population den...
 6   Population growth rate Natural increase Net re...
 7   World Africa Asia Europe North America Oceania...
 8   Age at childbearing Age at first marriage Age ...
 9   Antidepressant consumption Antiviral medicatio...
 10  Bloomberg Innovation Index Education Index Glo...
 11  Access to financial services Development aid d...
 12    List of international rankings Lists by country  ,
                                             vteWorld  \
 0  AfghanistanAlbaniaAlgeriaAndorraAngolaAntigua ...

                                           vteWorld.1
 0  AfghanistanAlbaniaAlgeriaAndorraAngolaAntigua ...  ]

In [42]:
len(tables)

3

In [49]:
tables[0]

,Location,Population,% of world,Date,Source (official or from the United Nations),Notes
0,World,8232000000,100%,13 Jun 2025,UN projection[1][3],NaN
1,India,1417492000,17.2%,1 Jul 2025,Official projection[4],[b]
2,China,1404890000,17.0%,31 Dec 2025,Official estimate[5],[c]
3,United States,341784857,4.1%,1 Jul 2025,Official estimate[6],[d]
4,Indonesia,288315089,3.5%,31 Dec 2025,National annual projection[7],NaN
...,...,...,...,...,...,...
235,Christmas Island (Australia),1692,0%,1 Jan 2021,2021 Census[248],NaN
236,Niue (New Zealand),1681,0%,11 Nov 2022,2022 Census[249],NaN
237,Vatican City,882,0%,31 Dec 2024,Official figure[250],[ah]
238,Cocos (Keeling) Islands (Australia),593,0%,30 Jun 2020,2021 Census[251],NaN
239,Pitcairn Islands (UK),35,0%,1 Jul 2023,Official estimate[252],NaN

In [44]:
type(tables)

list

In [50]:
tables[0].columns

Index(['Location', 'Population', '% of world', 'Date',
       'Source (official or from the United Nations)', 'Notes'],
      dtype='object')

In [52]:
df3 = tables[0]+tables[1]+tables[1]
df3

,% of world,Date,Location,Notes,Population,Source (official or from the United Nations),vteLists of countries by population statistics,vteLists of countries by population statistics.1
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
type(df3)

pandas.core.frame.DataFrame

In [54]:
df3.columns

Index(['% of world', 'Date', 'Location', 'Notes', 'Population',
       'Source (official or from the United Nations)',
       'vteLists of countries by population statistics',
       'vteLists of countries by population statistics.1'],
      dtype='object')

In [1]:
import pandas as pd

In [2]:
df4 = pd.read_csv("Titanic-Dataset.csv")
df4

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df4.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
df4.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [7]:
df4.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
df4.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [9]:
df4.dtypes[df4.dtypes =="object"]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [10]:
df4[df4.dtypes[df4.dtypes =="object"].index].describe()

                       Name   Sex  Ticket Cabin Embarked
count                   891   891     891   204      889
unique                  891     2     681   147        3
top     Dooley, Mr. Patrick  male  347082    G6        S
freq                      1   577       7     4      644

In [11]:
df4[df4.dtypes[df4.dtypes =="int64"].index].describe()

       PassengerId    Survived      Pclass       SibSp       Parch
count   891.000000  891.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642    0.523008    0.381594
std     257.353842    0.486592    0.836071    1.102743    0.806057
min       1.000000    0.000000    1.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000    0.000000    0.000000
50%     446.000000    0.000000    3.000000    0.000000    0.000000
75%     668.500000    1.000000    3.000000    1.000000    0.000000
max     891.000000    1.000000    3.000000    8.000000    6.000000

In [12]:
df4[df4.dtypes[df4.dtypes =="float64"].index].describe()

              Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [13]:
df4[["Ticket"]]

               Ticket
0           A/5 21171
1            PC 17599
2    STON/O2. 3101282
3              113803
4              373450
..                ...
886            211536
887            112053
888        W./C. 6607
889            111369
890            370376

[891 rows x 1 columns]

In [14]:
df4[["Ticket"]][4:15]

       Ticket
4      373450
5      330877
6       17463
7      349909
8      347742
9      237736
10    PP 9549
11     113783
12  A/5. 2151
13     347082
14     350406

In [28]:
df4[["Ticket","Age"]][1:10:2]

     Ticket   Age
1  PC 17599  38.0
3    113803  35.0
5    330877   NaN
7    349909   2.0
9    237736  14.0

In [29]:
df4.head(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [31]:
df4["'new_col"] = 0
df4

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,'new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

In [ ]:
# df4.insert(loc = 3, column="Food", value = 0)
df4

,PassengerId,Survived,Pclass,Food,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,'new_col
0,1,0,3,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,0,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,1,0,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,1,1,0,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

In [3]:
df4["Pclass"]

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [4]:
pd.Categorical(df4["Pclass"])

[3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1, 2, 3]

In [6]:
df4["Cabin"].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [10]:
df4[["Age","Name"]][df4["Age"] >= 15]

      Age                                               Name
0    22.0                            Braund, Mr. Owen Harris
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    26.0                             Heikkinen, Miss. Laina
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4    35.0                           Allen, Mr. William Henry
..    ...                                                ...
885  39.0               Rice, Mrs. William (Margaret Norton)
886  27.0                              Montvila, Rev. Juozas
887  19.0                       Graham, Miss. Margaret Edith
889  26.0                              Behr, Mr. Karl Howell
890  32.0                                Dooley, Mr. Patrick

[636 rows x 2 columns]

In [11]:
df4.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [14]:
df4["Fare"][df4["Fare"] > 32]

1       71.2833
3       53.1000
6       51.8625
23      35.5000
27     263.0000
         ...
856    164.8667
863     69.5500
867     50.4958
871     52.5542
879     83.1583
Name: Fare, Length: 211, dtype: float64

In [15]:
df4

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [17]:
df4[["PassengerId","Survived","Pclass"]][:5]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

# iloc and loc

In [19]:
df4.iloc[:5,:5]

,PassengerId,Survived,Pclass,Name,Sex
0,1,0,3,"Braund, Mr. Owen Harris",male
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female
2,3,1,3,"Heikkinen, Miss. Laina",female
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female
4,5,0,3,"Allen, Mr. William Henry",male

In [20]:
df4.loc[0:6,["Sex","Age","Parch"]]

      Sex   Age  Parch
0    male  22.0      0
1  female  38.0      0
2  female  26.0      0
3  female  35.0      0
4    male  35.0      0
5    male   NaN      0
6    male  54.0      0