# 1. What is a DataFrame?

DataFrame is a 2-dimensional labeled data structure.

Think:

Series = One Column

DataFrame = Multiple Columns

A DataFrame can be viewed as:

1. Spreadsheet
2. SQL Table
3. Dictionary of Series

Rows -> Records

Columns -> Features

# 2. DataFrame Creation: From Dict of Series

Dictionary keys become column names.

Each Series becomes a column.

Pandas aligns Series using index labels.

Missing values become NaN.

In [1]:
import pandas as pd

In [3]:
"Example 1"


d = {
    "one":pd.Series(
        [10,20,30],
        index=['a','b','c']
    ),
    "two":pd.Series(
        [10,20,30,40],
        index=['a','b','c','d']
    )
}
print(d)

{'one': a    10
b    20
c    30
dtype: int64, 'two': a    10
b    20
c    30
d    40
dtype: int64}

In [4]:
df = pd.DataFrame(d)
print(df)

    one  two
a  10.0   10
b  20.0   20
c  30.0   30
d   NaN   40

## 2.1 Custom Index

index parameter controls row labels.
```
Example:

pd.DataFrame(
    d,
    index=["d","b","a"]
)
```

```    
    Only rows d, b, a are kept.

    Rows not listed are removed.

    Missing values become NaN.
    ```

In [ ]:
"Example 1"


d = {
    "one":pd.Series(
        [10,20,30],
        index=['a','b','c']
    ),
    "two":pd.Series(
        [10,20,30,40],
        index=['a','b','c','d']
    )
}

In [5]:
pd.DataFrame(
    d,
    index=['b','a','d']
)

    one  two
b  20.0   20
a  10.0   10
d   NaN   40

## 2.2 Custom Columns

columns parameter controls column labels.
```
Example:

pd.DataFrame(
    d,
    columns=["two","three"]
)

```

```
    Column "two" exists.

    Column "three" does not exist.

    Result:

    Column "three" is filled with NaN.

```

In [7]:
"Example 1"



d = {
    "one":pd.Series(
        [10,20,30],
        index=['a','b','c']
    ),
    "two":pd.Series(
        [10,20,30,40],
        index=['a','b','c','d']
    )
}

pd.DataFrame(
    d,
    index=['d','b','a'],
    columns=['two','three']
)

   two three
d   40   NaN
b   20   NaN
a   10   NaN

## 2.3 DataFrame Labels

Pandas displays them as Index objects, not Python lists.

- df.index -> Returns row labels

Example:

Index(['a', 'b'], dtype='object')

-------------------

- df.columns -> Returns column labels

Example:

Index(['one', 'two'], dtype='object')

In [12]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
df.columns

Index(['one', 'two'], dtype='object')

# 3. DataFrame from Dict of Lists

Dictionary keys become column names.

Lists become column values.

All lists must have the same length.

- Default index:0,1,2,...

In [20]:
"Example 1"


d = {
    'one': [1,2,3,4],
    'two': [2,3,4,5]
}

pd.DataFrame(d)

   one  two
0    1    2
1    2    3
2    3    4
3    4    5

### Custom Index with Dict of Lists

Use index= to specify row labels.

Example:

pd.DataFrame(
    data,
    index=["A","B","C"]
)

Rules:

1. Length of index must equal number of rows.
2. Data remains unchanged.
3. Only row labels are modified.

In [ ]:
"Example 2"

d = {
    "one": [1.0,2.0,3.0,4.0],
    "two": [4.0,3.0,2.0,1.0]
}

pd.DataFrame(
    d,
    index=["a","b","c","d"]
)

   one  two
a  1.0  4.0
b  2.0  3.0
c  3.0  2.0
d  4.0  1.0

# 4. List of dictionaries

1. DataFrame from List of Dicts
2. Each dictionary represents one row.
3. Dictionary keys become column names.
4. Dictionary values become row values.
5. Missing keys are filled with NaN.
6. Commonly used when working with JSON, APIs, and web scraping data.

```
Pandas takes the union of all keys from all dictionaries.
```

In [2]:
import pandas as pd

In [3]:
"Example 1"

s= [
    {
        'one':1,
        'two':2
    },
    {
        'hello':"world",
        'data':'science'
    }
]

pd.DataFrame(s)

   one  two  hello     data
0  1.0  2.0    NaN      NaN
1  NaN  NaN  world  science

In [7]:
"Example 1"


data = [
    {"name":"Ram","age":20},
    {"name":"Shyam"},
    {"name":"Mohan","age":22}
]

df = pd.DataFrame(data)
df

    name   age
0    Ram  20.0
1  Shyam   NaN
2  Mohan  22.0

# 5. Creating a DataFrame from a Series

DataFrame from Series
1. A Series can be converted into a DataFrame.
2. The resulting DataFrame contains one column.
3. Series index becomes DataFrame index.
4. Series name becomes DataFrame column name

In [ ]:
"Example 1"

import pandas as pd

ser = pd.Series(
    [10,20,30],
    # name="Marks"
)

df = pd.DataFrame(ser)

print(df)

    0
0  10
1  20
2  30

In [9]:
"Example 2"

ser = pd.Series(
    [85,90,78],
    index=["Ram","Shyam","Mohan"],
    name="Marks"
)

pd.DataFrame(ser)

       Marks
Ram       85
Shyam     90
Mohan     78

# 6. Column Selection (df["column"])

Column Selection
```
Syntax:

df["column_name"]
```
- Used to select a single column.
- Returns a Series.
- Column name must exist.
- Non-existing column raises KeyError.

In [4]:
df = pd.DataFrame({
    "Name":["Ram","Shyam","Mohan"],
    "Marks":[85,90,78]
})
df

    Name  Marks
0    Ram     85
1  Shyam     90
2  Mohan     78

In [ ]:
print(type(df["Marks"]))
df["Marks"]

<class 'pandas.core.series.Series'>

0    85
1    90
2    78
Name: Marks, dtype: int64

In [5]:
df["Marks"].mean()

np.float64(84.33333333333333)

## 6.1 Multiple Column Selection

Syntax:

- df[["col1","col2"]]
- Used to select multiple columns.
- Returns a DataFrame.
- Column names are passed inside a list.

In [ ]:
"Example 1"

import pandas as pd

df = pd.DataFrame({
    "Name":["Ram","Shyam","Mohan"],
    "Age":[20,21,19],
    "Marks":[85,90,78]
})

In [9]:
print(df[['Name','Marks']])
print(type(df[['Name','Marks']]))

    Name  Marks
0    Ram     85
1  Shyam     90
2  Mohan     78
<class 'pandas.core.frame.DataFrame'>

In [10]:
print(df["Marks"])
print(type(df["Marks"]))

0    85
1    90
2    78
Name: Marks, dtype: int64
<class 'pandas.core.series.Series'>

In [12]:
print(df[["Marks"]])
print(type(df[["Marks"]]))

   Marks
0     85
1     90
2     78
<class 'pandas.core.frame.DataFrame'>

# 7. Adding New Columns

In Data Science, we often create new features from existing columns.

Adding New Columns
```
Syntax:

df["new_column"] = value
```
Possible values:

- Scalar
- List
- Series
- Calculation from existing columns

## 7.1 Method 1: Add a Constant Value

In [ ]:
"Example 1"

df = pd.DataFrame({
    "Marks":[20,30,40,50]
})
print(type(df))
print((df))

<class 'pandas.core.frame.DataFrame'>
   Marks
0     20
1     30
2     40
3     50

In [16]:
df['Age'] = 18

print(df)
print(type(df))

   Marks  Age
0     20   18
1     30   18
2     40   18
3     50   18
<class 'pandas.core.frame.DataFrame'>

## Method 2: Create Column from Existing Columns

In [17]:
"Example 1"

df = pd.DataFrame({
    "Marks":[80,90,70],
    "Bonus":[5,5,5]
})
df["Total"]  =  df["Marks"] + df["Bonus"]

print(type(df))
print((df))

<class 'pandas.core.frame.DataFrame'>
   Marks  Bonus  Total
0     80      5     85
1     90      5     95
2     70      5     75

## Method 3: Add Using a List

In [19]:
"Example 1"


df = pd.DataFrame({
    "Marks":[80,90,70],
    "Bonus":[5,5,5]
})


df["Grade"] = ['A','B',"C"]

In [20]:
print(type(df))
print((df))

<class 'pandas.core.frame.DataFrame'>
   Marks  Bonus Grade
0     80      5     A
1     90      5     B
2     70      5     C

# 8. Deleting Columns

## 8.1 Method 1: del

1. The column is permanently removed from the DataFrame.

2. Deletes the column.  You don't get the deleted column back.

```
Syntax:

del df["column_name"]
```

In [21]:
"Example 1"

df = pd.DataFrame({
    "A":[1,2],
    "B":[3,4]
})

del df["B"]

print(df)

   A
0  1
1  2

## 8.2 Method 2: pop()

1. Deletes and returns the columns as Series..

```
Syntax:

df.pop("column_name")
```

In [22]:
"Example 1"

df = pd.DataFrame({
    "A":[1,2],
    "B":[3,4]
})

x = df.pop("B")

print(df)

   A
0  1
1  2

In [25]:
print(x)
print(type(x))

0    3
1    4
Name: B, dtype: int64
<class 'pandas.core.series.Series'>

# 9. df.insert()

Used to insert a column at a specific position.

```

Syntax
df.insert(
    loc,
    column_name,
    values
)
```
Meaning
1. loc → Position where column should be inserted
2. column_name → Name of new column
3. values → Data for column

In [26]:
"Example 1"


df = pd.DataFrame({
    "A":[1,2],
    "B":[3,4]
})

df.insert(0, "X", [10,20])

print(df)

    X  A  B
0  10  1  3
1  20  2  4

In [28]:
"Example 2"

df = pd.DataFrame({
    "A":[1,2],
    "B":[3,4]
})

df.insert(1, "C", [5,6])
df

   A  C  B
0  1  5  3
1  2  6  4

# 10. Row Selection with loc

Used for label-based row selection.

Syntax:

df.loc["label"]

Example:

df.loc["b"]

Returns:
```
Name     Shyam
Marks       90

Uses row labels.
Returns a Series for a single row.
Raises KeyError if label does not exist.

```

In [31]:
"Example 1"

df = pd.DataFrame(
    {
        "Name":["Ram","Shyam","Mohan"],
        "Marks":[80,90,70]
    },
    index=["a","b","c"]
)

df.loc["b"]

Name     Shyam
Marks       90
Name: b, dtype: object

## 10.1 single row

In [32]:
"Example 2 "


df = pd.DataFrame(
    {
        "City":["Delhi","Mumbai","Pune"],
        "Population":[30,20,10]
    },
    index=["x","y","z"]
)

print(df.loc["z"])

City          Pune
Population      10
Name: z, dtype: object

## 10.2 multiple rows

In [36]:
"Example 1"

df = pd.DataFrame(
    {
        "Name":["Ram","Shyam","Mohan"],
        "Marks":[80,90,70]
    },
    index=["a","b","c"]
)
print(df.loc[["a","c"]])
print(type(df.loc[["a","c"]]))

    Name  Marks
a    Ram     80
c  Mohan     70
<class 'pandas.core.frame.DataFrame'>

## 10.3 Single Cell  ->  loc[row, column]

Returns single value only.

In [37]:
"Example 1"

df = pd.DataFrame(
    {
        "City":["Delhi","Mumbai","Pune"],
        "Population":[30,20,10]
    },
    index=["x","y","z"]
)

df.loc["z", "Population"]

np.int64(10)

## 10.4 Selecting Rows and Columns Together

Used to select specific rows and specific columns.

```
syntax: df.loc[[rows],[columns]]

df.loc[rows, columns]


df.loc[
    which rows,
    which columns
]
```

In [42]:
"Example 1"

df = pd.DataFrame(
    {
        "Name":["Ram","Shyam","Mohan"],
        "Marks":[80,90,70],
        "Age":[20,21,19]
    },
    index=["a","b","c"]
)

print(df.loc[['a','c'],["Name","Age"]])
df.loc[['a'],["Name"]]

    Name  Age
a    Ram   20
c  Mohan   19

  Name
a  Ram

## 10.5 Label Slicing

Includes both start and end labels.

In [43]:
df = pd.DataFrame(
    {"Marks":[80,90,70]},
    index=["a","b","c"]
)
df.loc["a":"c"]

   Marks
a     80
b     90
c     70

# 11. iloc (Integer Location)

iloc only accepts integer positions.
- - Used for position-based selection.

In [44]:
"Example 1"

df = pd.DataFrame(
    {
        "City":["Delhi","Mumbai","Pune"]
    },
    index=["x","y","z"]
)

print(df.iloc[2])

City    Pune
Name: z, dtype: object

## 11.1 Multiple Rows with iloc

 - df.iloc[rows, columns]

In [ ]:
"Example 1"

df = pd.DataFrame(
    {
        "City":["Delhi","Mumbai","Pune"]
    },
    index=['x','y','z']
)

print(df.iloc[[1,2]])
print(type(df.iloc[[1,2]]))

     City
y  Mumbai
z    Pune
<class 'pandas.core.frame.DataFrame'>

In [ ]:
df.iloc["y"]  ## Gives error

## 11.2 iloc[row_position, column_position]

```
df.loc[row_label, column_label]

- Returns a single cell

```

In [57]:
"Example 1"

df = pd.DataFrame(
    {
        "Name":["Ram","Shyam","Mohan"],
        "Marks":[80,90,70]
    }
)


print(df.iloc[0,1])
# print(df.iloc[[0,1],0])
df.iloc[0,0]

80

'Ram'

##  11.3 multiple_row and multiple_columns

df.iloc[row_positions, column_positions]

In [59]:
"Example 1"

df = pd.DataFrame(
    {
        "Name":["Ram","Shyam","Mohan"],
        "Marks":[80,90,70]
    }
)

print(df.iloc[[0,1],0])

0      Ram
1    Shyam
Name: Name, dtype: object