# 1. What is a DataFrame?

DataFrame is a 2-dimensional labeled data structure.

Think:

Series = One Column

DataFrame = Multiple Columns

A DataFrame can be viewed as:

1. Spreadsheet
2. SQL Table
3. Dictionary of Series

Rows -> Records

Columns -> Features

# 2. DataFrame Creation: From Dict of Series

Dictionary keys become column names.

Each Series becomes a column.

Pandas aligns Series using index labels.

Missing values become NaN.

In [1]:
import pandas as pd

In [3]:
"Example 1"


d = {
    "one":pd.Series(
        [10,20,30],
        index=['a','b','c']
    ),
    "two":pd.Series(
        [10,20,30,40],
        index=['a','b','c','d']
    )
}
print(d)

{'one': a    10
b    20
c    30
dtype: int64, 'two': a    10
b    20
c    30
d    40
dtype: int64}

In [4]:
df = pd.DataFrame(d)
print(df)

    one  two
a  10.0   10
b  20.0   20
c  30.0   30
d   NaN   40

## 2.1 Custom Index

index parameter controls row labels.
```
Example:

pd.DataFrame(
    d,
    index=["d","b","a"]
)
```

```    
    Only rows d, b, a are kept.

    Rows not listed are removed.

    Missing values become NaN.
    ```

In [ ]:
"Example 1"


d = {
    "one":pd.Series(
        [10,20,30],
        index=['a','b','c']
    ),
    "two":pd.Series(
        [10,20,30,40],
        index=['a','b','c','d']
    )
}

In [5]:
pd.DataFrame(
    d,
    index=['b','a','d']
)

    one  two
b  20.0   20
a  10.0   10
d   NaN   40

## 2.2 Custom Columns

columns parameter controls column labels.
```
Example:

pd.DataFrame(
    d,
    columns=["two","three"]
)

```

```
    Column "two" exists.

    Column "three" does not exist.

    Result:

    Column "three" is filled with NaN.

```

In [7]:
"Example 1"



d = {
    "one":pd.Series(
        [10,20,30],
        index=['a','b','c']
    ),
    "two":pd.Series(
        [10,20,30,40],
        index=['a','b','c','d']
    )
}

pd.DataFrame(
    d,
    index=['d','b','a'],
    columns=['two','three']
)

   two three
d   40   NaN
b   20   NaN
a   10   NaN

## 2.3 DataFrame Labels

Pandas displays them as Index objects, not Python lists.

- df.index -> Returns row labels

Example:

Index(['a', 'b'], dtype='object')

-------------------

- df.columns -> Returns column labels

Example:

Index(['one', 'two'], dtype='object')

In [12]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
df.columns

Index(['one', 'two'], dtype='object')

# 3. DataFrame from Dict of Lists

Dictionary keys become column names.

Lists become column values.

All lists must have the same length.

- Default index:0,1,2,...

In [20]:
"Example 1"


d = {
    'one': [1,2,3,4],
    'two': [2,3,4,5]
}

pd.DataFrame(d)

   one  two
0    1    2
1    2    3
2    3    4
3    4    5

### Custom Index with Dict of Lists

Use index= to specify row labels.

Example:

pd.DataFrame(
    data,
    index=["A","B","C"]
)

Rules:

1. Length of index must equal number of rows.
2. Data remains unchanged.
3. Only row labels are modified.

In [ ]:
"Example 2"

d = {
    "one": [1.0,2.0,3.0,4.0],
    "two": [4.0,3.0,2.0,1.0]
}

pd.DataFrame(
    d,
    index=["a","b","c","d"]
)

   one  two
a  1.0  4.0
b  2.0  3.0
c  3.0  2.0
d  4.0  1.0