In [1]:
import pandas as pd

In [2]:
import pandas as pd

In [14]:
df = pd.read_csv("free-taxonomy.csv")
df.head(3)

,name,id,parent_name,parent_id,vocabulary,x-description,x-notes,services
0,Emergency,1101,0,0.0,Open Eligibility Human Services,"Services for psychiatric emergencies, emergenc...",NaN,NaN
1,Food,1102,0,0.0,Open Eligibility Human Services,"Services for free meals, food pantries, help p...",NaN,NaN
2,Housing,1103,0,0.0,Open Eligibility Human Services,"Services for emergency, short-term and long-te...",NaN,NaN

In [10]:
df

,name,id,parent_name,parent_id,vocabulary,x-description,x-notes,services
0,Emergency,1101,0,0.0,Open Eligibility Human Services,"Services for psychiatric emergencies, emergenc...",NaN,NaN
1,Food,1102,0,0.0,Open Eligibility Human Services,"Services for free meals, food pantries, help p...",NaN,NaN
2,Housing,1103,0,0.0,Open Eligibility Human Services,"Services for emergency, short-term and long-te...",NaN,NaN
3,Goods,1104,0,0.0,Open Eligibility Human Services,"Services for clothing, furniture, baby supplie...",NaN,NaN
4,Transit,1105,0,0.0,Open Eligibility Human Services,"Services for bus passes, transportation to sch...",NaN,NaN
...,...,...,...,...,...,...,...,...
322,In Danger,20089,Urgency,20087.0,Open Eligibility Human Situations,NaN,NaN,NaN
323,Chronic Illness,20090,Health,1106.0,Open Eligibility Human Situations,NaN,NaN,NaN
324,Spouses,20091,Role,20072.0,Open Eligibility Human Situations,NaN,NaN,NaN
325,Dependents,20092,Role,20072.0,Open Eligibility Human Situations,NaN,NaN,NaN
326,Intellectual Disability,20093,Disability,20017.0,Open Eligibility Human Situations,NaN,NaN,NaN

# 1.drop missing values

In [15]:
df.dropna()

Empty DataFrame
Columns: [name, id, parent_name, parent_id, vocabulary, x-description, x-notes, services]
Index: []

In [16]:
df

,name,id,parent_name,parent_id,vocabulary,x-description,x-notes,services
0,Emergency,1101,0,0.0,Open Eligibility Human Services,"Services for psychiatric emergencies, emergenc...",NaN,NaN
1,Food,1102,0,0.0,Open Eligibility Human Services,"Services for free meals, food pantries, help p...",NaN,NaN
2,Housing,1103,0,0.0,Open Eligibility Human Services,"Services for emergency, short-term and long-te...",NaN,NaN
3,Goods,1104,0,0.0,Open Eligibility Human Services,"Services for clothing, furniture, baby supplie...",NaN,NaN
4,Transit,1105,0,0.0,Open Eligibility Human Services,"Services for bus passes, transportation to sch...",NaN,NaN
...,...,...,...,...,...,...,...,...
322,In Danger,20089,Urgency,20087.0,Open Eligibility Human Situations,NaN,NaN,NaN
323,Chronic Illness,20090,Health,1106.0,Open Eligibility Human Situations,NaN,NaN,NaN
324,Spouses,20091,Role,20072.0,Open Eligibility Human Situations,NaN,NaN,NaN
325,Dependents,20092,Role,20072.0,Open Eligibility Human Situations,NaN,NaN,NaN
326,Intellectual Disability,20093,Disability,20017.0,Open Eligibility Human Situations,NaN,NaN,NaN

In [17]:
df.columns

Index(['name', 'id', 'parent_name', 'parent_id', 'vocabulary', 'x-description',
       'x-notes', 'services'],
      dtype='object')

In [21]:
df["parent_name"].tail(20)

307          Role
308          Role
309          Role
310           NaN
311     Sexuality
312           NaN
313     Survivors
314     Survivors
315     Survivors
316     Survivors
317     Survivors
318     Survivors
319     Survivors
320           NaN
321       Urgency
322       Urgency
323        Health
324          Role
325          Role
326    Disability
Name: parent_name, dtype: object

## 1.1 drop missing values based on  columns

In [29]:
df.dropna(axis=1,inplace=True)

In [30]:
df

                        name     id                         vocabulary
0                  Emergency   1101    Open Eligibility Human Services
1                       Food   1102    Open Eligibility Human Services
2                    Housing   1103    Open Eligibility Human Services
3                      Goods   1104    Open Eligibility Human Services
4                    Transit   1105    Open Eligibility Human Services
..                       ...    ...                                ...
322                In Danger  20089  Open Eligibility Human Situations
323          Chronic Illness  20090  Open Eligibility Human Situations
324                  Spouses  20091  Open Eligibility Human Situations
325               Dependents  20092  Open Eligibility Human Situations
326  Intellectual Disability  20093  Open Eligibility Human Situations

[327 rows x 3 columns]

## 1.1 drop missing values based on rows.

In [34]:
df.dropna(axis=0)

                        name     id                         vocabulary
0                  Emergency   1101    Open Eligibility Human Services
1                       Food   1102    Open Eligibility Human Services
2                    Housing   1103    Open Eligibility Human Services
3                      Goods   1104    Open Eligibility Human Services
4                    Transit   1105    Open Eligibility Human Services
..                       ...    ...                                ...
322                In Danger  20089  Open Eligibility Human Situations
323          Chronic Illness  20090  Open Eligibility Human Situations
324                  Spouses  20091  Open Eligibility Human Situations
325               Dependents  20092  Open Eligibility Human Situations
326  Intellectual Disability  20093  Open Eligibility Human Situations

[327 rows x 3 columns]