# Topic 1: duplicated()

duplicated() checks whether a row is a duplicate of a previous row.

Why Use It?
- Used to identify repeated records in a dataset.

```
Syntax

df.duplicated()
df.duplicated().sum()
```
Important Points

- Returns True for duplicate rows.
- Returns False for first occurrence.
- Does not remove duplicates.
- Usually used before drop_duplicates().

In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("netflix_titles.csv")

In [10]:
df.head(4)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [15]:
df.shape

(8807, 12)

In [16]:
list(df.columns)

['show_id',
 'type',
 'title',
 'director',
 'cast',
 'country',
 'date_added',
 'release_year',
 'rating',
 'duration',
 'listed_in',
 'description']

---------------

In [12]:
df.duplicated().sum()

np.int64(0)

```
It means:

There are no completely identical rows in the dataset.

So we can say:

Exact Duplicate Rows = 0
```

---------------------------------------------

In [13]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

## Duplicate based on specific columns

Suppose we want to check whether the same property appears multiple times.

```
We can do:

df["PID"].duplicated().sum()

or

df.duplicated(subset=["PID"]).sum()

This checks duplicates only on the PID column.
```

In [17]:
df["show_id"].duplicated().sum()

np.int64(0)

In [18]:
df["title"].duplicated().sum()

np.int64(0)

# Topic 2: drop_duplicates()

Removes duplicate rows from a DataFrame.

Why Use It?
- Used to eliminate repeated records and prevent incorrect analysis.

```
Syntax

df.drop_duplicates()
df.drop_duplicates(subset=["column"])
df.drop_duplicates(inplace=True)


```

Important Points

- Keeps the first occurrence by default.
- Returns a new DataFrame unless inplace=True.
- Can remove duplicates based on specific columns using subset.
- Always inspect duplicates before deleting them.

## Important Parameter

### 1) keep

Default:

```
df.drop_duplicates(keep="first")
- Keep first occurrence.

Other options:
df.drop_duplicates(keep="last")
- Keep last occurrence.

df.drop_duplicates(keep=False)
- Remove all duplicated records.
```

# Topic 3: rename()

rename() is used to change row labels or column names.

Why Use It?
- Makes column names more readable and meaningful.

```
Syntax

df.rename(columns={
    "old_name": "new_name"
})
```
Important Points

- Original DataFrame is unchanged unless assigned back or inplace=True.
- Can rename one or multiple columns.
- Mostly used for column names.

In [19]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [20]:
df['listed_in']

0                                           Documentaries
1         International TV Shows, TV Dramas, TV Mysteries
2       Crime TV Shows, International TV Shows, TV Act...
3                                  Docuseries, Reality TV
4       International TV Shows, Romantic TV Shows, TV ...
                              ...
8802                       Cult Movies, Dramas, Thrillers
8803               Kids' TV, Korean TV Shows, TV Comedies
8804                              Comedies, Horror Movies
8805                   Children & Family Movies, Comedies
8806       Dramas, International Movies, Music & Musicals
Name: listed_in, Length: 8807, dtype: object

---------------------------------------------------------------------

rename column names:
1. listed_in -> genres
2. date added -> netflix_added_date

--------------------------------------------------------------------------