# Topic 1: sort_values()

sort_values() is used to sort data based on column values.


Used to find:

- Highest values
- Lowest values
- Latest records
- Top performers

```
Syntax

df.sort_values("column_name")
```
Important Points

- Default: Ascending order (small → large, A → Z)
- Returns a new DataFrame.
- Original DataFrame remains unchanged unless assigned back.
- One of the most frequently used Pandas functions.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("netflix_titles.csv")
df.head(4)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."

In [32]:
df.shape

(8807, 12)

In [21]:
df["release_year"].sort_values()

4250    1925
7790    1942
8205    1942
8739    1943
8763    1943
        ...
3       2021
2       2021
18      2021
1       2021
68      2021
Name: release_year, Length: 8807, dtype: int64

In [35]:
df.sort_values("release_year")[["title","release_year"]].head(20)

                                                 title  release_year
4250                 Pioneers: First Women Filmmakers*          1925
7790                                    Prelude to War          1942
8205                              The Battle of Midway          1942
8739                Why We Fight: The Battle of Russia          1943
8763                   WWII: Report from the Aleutians          1943
8660     Undercover: How to Operate Behind Enemy Lines          1943
8419  The Memphis Belle: A Story of a\nFlying Fortress          1944
8436                                 The Negro Soldier          1944
8640                                  Tunisian Victory          1944
7219                           Know Your Enemy - Japan          1945
1331               Five Came Back: The Reference Films          1945
7575                          Nazi Concentration Camps          1945
7930                                        San Pietro          1945
7743               Pioneers of African-American Cinema          1946
7294                                Let There Be Light          1946
8587                                       Thunderbolt          1947
2375                                   The Blazing Sun          1954
1699                                   White Christmas          1954
7839                             Rebel Without a Cause          1955
8506                                 The Sign of Venus          1955

In [39]:
df["release_year"].sort_values(ascending=False)

1       2021
2       2021
3       2021
31      2021
30      2021
        ...
8739    1943
8660    1943
7790    1942
8205    1942
4250    1925
Name: release_year, Length: 8807, dtype: int64

In [42]:
df.sort_values(
    "release_year",
    ascending=False
)[["title","release_year"]].head(10)

                                              title  release_year
1                                     Blood & Water          2021
2                                         Ganglands          2021
3                             Jailbirds New Orleans          2021
31                               Chicago Party Aunt          2021
30                                  Ankahi Kahaniya          2021
25                             Love on the Spectrum          2021
23     Go! Go! Cory Carson: Chrissy Takes the Wheel          2021
20  Monsters Inside: The 24 Faces of Billy Milligan          2021
19                                           Jaguar          2021
18                                        Intrusion          2021

## Multiple Column Sorting

Sort data using more than one column.
```
Syntax

df.sort_values(
    ["col1", "col2"]
)
```
Important Points

- First column = primary sorting key
- Second column = tie-breaker
- Third column = tie-breaker for second column
- Very common in real datasets

```

df.sort_values(
    ["release_year", "title"]
)
```

Step 1: Sort by release_year
- 2020
- 2021
- 2021

Step 2: For rows having same year
- Now Pandas uses the second column: title
- and sorts alphabetically:

In [43]:
"Example 1"


df.sort_values(['release_year','title'])[['title',"release_year"]].head(10)

                                                 title  release_year
4250                 Pioneers: First Women Filmmakers*          1925
7790                                    Prelude to War          1942
8205                              The Battle of Midway          1942
8660     Undercover: How to Operate Behind Enemy Lines          1943
8763                   WWII: Report from the Aleutians          1943
8739                Why We Fight: The Battle of Russia          1943
8419  The Memphis Belle: A Story of a\nFlying Fortress          1944
8436                                 The Negro Soldier          1944
8640                                  Tunisian Victory          1944
1331               Five Came Back: The Reference Films          1945

--------------------------------------------------
```
df.sort_values(
    ["release_year", "title"],
    ascending=[False, True]
)

- release_year → False
- title → True
```
---------------------------------------------------

In [46]:
"Example 2"

df.sort_values(
    ["release_year", "title"],
    ascending=[False, True]
).head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1373,s1374,TV Show,50M2,NaN,"Engin Öztürk, Kürşat Alnıaçık, Cengiz Bozkurt,...",Turkey,"January 27, 2021",2021,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Thrillers","Seeking to uncover the truth about his past, a..."
1150,s1151,Movie,7 Yards: The Chris Norton Story,Jonathon Link,Chris Norton,United States,"March 30, 2021",2021,TV-PG,93 min,Documentaries,The true story of former college football play...
850,s851,Movie,99 Songs,Vishwesh Krishnamoorthy,"Ehan Bhat, Edilsy Vargas, Manisha Koirala, Lis...",India,"May 21, 2021",2021,TV-14,131 min,"Dramas, International Movies, Music & Musicals",Challenged to compose 100 songs before he can ...
851,s852,Movie,99 Songs (Tamil),NaN,NaN,NaN,"May 21, 2021",2021,TV-14,131 min,"Dramas, International Movies, Music & Musicals",Challenged to compose 100 songs before he can ...
852,s853,Movie,99 Songs (Telugu),NaN,NaN,NaN,"May 21, 2021",2021,TV-14,131 min,"Dramas, International Movies, Music & Musicals",Challenged to compose 100 songs before he can ...

# Topic 2: sort_index()

Sorts a DataFrame by its index labels.

Why Use It?
Used when row order/index has become messy and needs to be arranged.
```
Syntax

df.sort_index()
```
Important Points

- Sorts index, not column values.
- Default = Ascending index order.
- Mostly useful after filtering, sorting, concatenation, etc.

In [51]:
df.sort_values(
    "release_year"
)[["title","release_year"]].head(10)

                                                 title  release_year
4250                 Pioneers: First Women Filmmakers*          1925
7790                                    Prelude to War          1942
8205                              The Battle of Midway          1942
8739                Why We Fight: The Battle of Russia          1943
8763                   WWII: Report from the Aleutians          1943
8660     Undercover: How to Operate Behind Enemy Lines          1943
8419  The Memphis Belle: A Story of a\nFlying Fortress          1944
8436                                 The Negro Soldier          1944
8640                                  Tunisian Victory          1944
7219                           Know Your Enemy - Japan          1945

In [52]:
df.sort_values(
    "release_year"
)[["title","release_year"]].head(10).sort_index()

                                                 title  release_year
4250                 Pioneers: First Women Filmmakers*          1925
7219                           Know Your Enemy - Japan          1945
7790                                    Prelude to War          1942
8205                              The Battle of Midway          1942
8419  The Memphis Belle: A Story of a\nFlying Fortress          1944
8436                                 The Negro Soldier          1944
8640                                  Tunisian Victory          1944
8660     Undercover: How to Operate Behind Enemy Lines          1943
8739                Why We Fight: The Battle of Russia          1943
8763                   WWII: Report from the Aleutians          1943