# GroupBy

groupby() splits data into groups based on a column and allows aggregate calculations on each group.

Why Use It?
- Used to summarize data by categories.

```
Common Operations

mean()
sum()
count()
max()
min()
size()

Syntax

df.groupby("column")
```

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("netflix_titles.csv")
df.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...

In [3]:
df.groupby("type")

In [4]:
df.groupby("type").size()

type
Movie      6131
TV Show    2676
dtype: int64

In [5]:
df["type"].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [17]:
df["type"].max()

'TV Show'

## Aggregation

In [18]:
df.groupby('type')['release_year'].mean()

type
Movie      2013.121514
TV Show    2016.605755
Name: release_year, dtype: float64

## Multiple Aggregations

agg() applies multiple functions at once.

In [31]:
df.groupby("type")["release_year"].agg(
    ['mean','min','max']
)

                mean   min   max
type
Movie    2013.121514  1942  2021
TV Show  2016.605755  1925  2021

## 1. GroupBy + Count

In [32]:
df.groupby('type')["release_year"].count()

type
Movie      6131
TV Show    2676
Name: release_year, dtype: int64

## 2. GroupBy + Multiple Columns

In [33]:
df.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...

In [34]:
df.groupby('country')

In [38]:
df.groupby(['type','rating']).count()

                  show_id  title  director  cast  country  date_added  \
type    rating
Movie   66 min          1      1         1     1        1           1
        74 min          1      1         1     1        1           1
        84 min          1      1         1     1        1           1
        G              41     41        41    40       41          41
        NC-17           3      3         2     3        3           3
        NR             75     75        75    58       75          75
        PG            287    287       286   279      281         287
        PG-13         490    490       489   477      482         490
        R             797    797       794   788      787         797
        TV-14        1427   1427      1393  1298     1307        1427
        TV-G          126    126       114   104      109         126
        TV-MA        2062   2062      1993  1894     1924        2062
        TV-PG         540    540       517   458      504         540
        TV-Y          131    131       105   115       84         131
        TV-Y7         139    139       123   131       83         139
        TV-Y7-FV        5      5         4     3        4           5
        UR              3      3         3     3        3           3
TV Show NR              5      5         0     5        5           4
        R               2      2         1     2        1           2
        TV-14         733    733        64   657      623         730
        TV-G           94     94         4    79       81          94
        TV-MA        1145   1145       124   987     1007        1143
        TV-PG         323    323        21   261      269         321
        TV-Y          176    176         7   153      143         175
        TV-Y7         195    195         9   179      153         194
        TV-Y7-FV        1      1         0     1        1           1

                  release_year  duration  listed_in  description
type    rating
Movie   66 min               1         0          1            1
        74 min               1         0          1            1
        84 min               1         0          1            1
        G                   41        41         41           41
        NC-17                3         3          3            3
        NR                  75        75         75           75
        PG                 287       287        287          287
        PG-13              490       490        490          490
        R                  797       797        797          797
        TV-14             1427      1427       1427         1427
        TV-G               126       126        126          126
        TV-MA             2062      2062       2062         2062
        TV-PG              540       540        540          540
        TV-Y               131       131        131          131
        TV-Y7              139       139        139          139
        TV-Y7-FV             5         5          5            5
        UR                   3         3          3            3
TV Show NR                   5         5          5            5
        R                    2         2          2            2
        TV-14              733       733        733          733
        TV-G                94        94         94           94
        TV-MA             1145      1145       1145         1145
        TV-PG              323       323        323          323
        TV-Y               176       176        176          176
        TV-Y7              195       195        195          195
        TV-Y7-FV             1         1          1            1

In [39]:
df.groupby('type').count()

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
type,,,,,,,,,,,
Movie,6131,6131,5943,5656,5691,6131,6131,6129,6128,6131,6131
TV Show,2676,2676,230,2326,2285,2666,2676,2674,2676,2676,2676

## 3. as_index=False ⭐⭐⭐

Default:

df.groupby("type")["release_year"].mean()

returns:

- type
- Movie
- TV Show

type index ban jata hai.

Kabhi-kabhi hum normal DataFrame chahte hain.

---------------------------------------------------------------------

# Practice

In [40]:
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

## question 1

Find top 5 ratings with most content.

In [44]:
df.groupby('rating').size()

rating
66 min         1
74 min         1
84 min         1
G             41
NC-17          3
NR            80
PG           287
PG-13        490
R            799
TV-14       2160
TV-G         220
TV-MA       3207
TV-PG        863
TV-Y         307
TV-Y7        334
TV-Y7-FV       6
UR             3
dtype: int64

## question 2:

Which year has the maximum Netflix content?

In [70]:
df.groupby("release_year").size().idxmax()

np.int64(2018)

## Question 3

In [71]:
df.head(4)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."

Which rating category has the maximum Netflix content?

In [72]:
df.groupby('rating').size().idxmax()

'TV-MA'

## question 4

Which rating category has the minimum Netflix content?

In [ ]:
df.groupby('rating').size() .idxmin()

'66 min'

## question 5

Which rating category has the 2nd highest Netflix content?

In [85]:
df.groupby('rating').size().sort_values(ascending=False).index[1]

'TV-14'

## question 6

How many Movies and TV Shows exist in each rating category?

In [7]:
df.groupby(['type','rating']).size()

type     rating
Movie    66 min         1
         74 min         1
         84 min         1
         G             41
         NC-17          3
         NR            75
         PG           287
         PG-13        490
         R            797
         TV-14       1427
         TV-G         126
         TV-MA       2062
         TV-PG        540
         TV-Y         131
         TV-Y7        139
         TV-Y7-FV       5
         UR             3
TV Show  NR             5
         R              2
         TV-14        733
         TV-G          94
         TV-MA       1145
         TV-PG        323
         TV-Y         176
         TV-Y7        195
         TV-Y7-FV       1
dtype: int64

## Question 7

How many Movies and TV Shows exist in each rating category?Which combination has the highest content?

In [ ]:
df.groupby(['type','rating']).size().idxmax()

('Movie', 'TV-MA')

In [14]:
df[df['rating'].isin(['66 min','74 min','84 min'])]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [15]:
df["rating"].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', '74 min', '84 min', '66 min', 'NR', nan,
       'TV-Y7-FV', 'UR'], dtype=object)

In [22]:
df[df['duration'].isnull()][['title','rating','duration']]

                                     title  rating duration
5541                       Louis C.K. 2017  74 min      NaN
5794                 Louis C.K.: Hilarious  84 min      NaN
5813  Louis C.K.: Live at the Comedy Store  66 min      NaN