In [1]:
import pandas as pd

In [2]:
import pandas as pd

In [14]:
df = pd.read_csv("free-taxonomy.csv")
df.head(3)

,name,id,parent_name,parent_id,vocabulary,x-description,x-notes,services
0,Emergency,1101,0,0.0,Open Eligibility Human Services,"Services for psychiatric emergencies, emergenc...",NaN,NaN
1,Food,1102,0,0.0,Open Eligibility Human Services,"Services for free meals, food pantries, help p...",NaN,NaN
2,Housing,1103,0,0.0,Open Eligibility Human Services,"Services for emergency, short-term and long-te...",NaN,NaN

In [10]:
df

,name,id,parent_name,parent_id,vocabulary,x-description,x-notes,services
0,Emergency,1101,0,0.0,Open Eligibility Human Services,"Services for psychiatric emergencies, emergenc...",NaN,NaN
1,Food,1102,0,0.0,Open Eligibility Human Services,"Services for free meals, food pantries, help p...",NaN,NaN
2,Housing,1103,0,0.0,Open Eligibility Human Services,"Services for emergency, short-term and long-te...",NaN,NaN
3,Goods,1104,0,0.0,Open Eligibility Human Services,"Services for clothing, furniture, baby supplie...",NaN,NaN
4,Transit,1105,0,0.0,Open Eligibility Human Services,"Services for bus passes, transportation to sch...",NaN,NaN
...,...,...,...,...,...,...,...,...
322,In Danger,20089,Urgency,20087.0,Open Eligibility Human Situations,NaN,NaN,NaN
323,Chronic Illness,20090,Health,1106.0,Open Eligibility Human Situations,NaN,NaN,NaN
324,Spouses,20091,Role,20072.0,Open Eligibility Human Situations,NaN,NaN,NaN
325,Dependents,20092,Role,20072.0,Open Eligibility Human Situations,NaN,NaN,NaN
326,Intellectual Disability,20093,Disability,20017.0,Open Eligibility Human Situations,NaN,NaN,NaN

# 1.drop missing values

- if any row have missing values it will remove that entire row.
- So for safe use axis.

In [15]:
df.dropna()

Empty DataFrame
Columns: [name, id, parent_name, parent_id, vocabulary, x-description, x-notes, services]
Index: []

In [16]:
df

,name,id,parent_name,parent_id,vocabulary,x-description,x-notes,services
0,Emergency,1101,0,0.0,Open Eligibility Human Services,"Services for psychiatric emergencies, emergenc...",NaN,NaN
1,Food,1102,0,0.0,Open Eligibility Human Services,"Services for free meals, food pantries, help p...",NaN,NaN
2,Housing,1103,0,0.0,Open Eligibility Human Services,"Services for emergency, short-term and long-te...",NaN,NaN
3,Goods,1104,0,0.0,Open Eligibility Human Services,"Services for clothing, furniture, baby supplie...",NaN,NaN
4,Transit,1105,0,0.0,Open Eligibility Human Services,"Services for bus passes, transportation to sch...",NaN,NaN
...,...,...,...,...,...,...,...,...
322,In Danger,20089,Urgency,20087.0,Open Eligibility Human Situations,NaN,NaN,NaN
323,Chronic Illness,20090,Health,1106.0,Open Eligibility Human Situations,NaN,NaN,NaN
324,Spouses,20091,Role,20072.0,Open Eligibility Human Situations,NaN,NaN,NaN
325,Dependents,20092,Role,20072.0,Open Eligibility Human Situations,NaN,NaN,NaN
326,Intellectual Disability,20093,Disability,20017.0,Open Eligibility Human Situations,NaN,NaN,NaN

In [17]:
df.columns

Index(['name', 'id', 'parent_name', 'parent_id', 'vocabulary', 'x-description',
       'x-notes', 'services'],
      dtype='object')

In [21]:
df["parent_name"].tail(20)

307          Role
308          Role
309          Role
310           NaN
311     Sexuality
312           NaN
313     Survivors
314     Survivors
315     Survivors
316     Survivors
317     Survivors
318     Survivors
319     Survivors
320           NaN
321       Urgency
322       Urgency
323        Health
324          Role
325          Role
326    Disability
Name: parent_name, dtype: object

## 1.1 drop missing values based on  columns

In [29]:
df.dropna(axis=1,inplace=True)

In [30]:
df

                        name     id                         vocabulary
0                  Emergency   1101    Open Eligibility Human Services
1                       Food   1102    Open Eligibility Human Services
2                    Housing   1103    Open Eligibility Human Services
3                      Goods   1104    Open Eligibility Human Services
4                    Transit   1105    Open Eligibility Human Services
..                       ...    ...                                ...
322                In Danger  20089  Open Eligibility Human Situations
323          Chronic Illness  20090  Open Eligibility Human Situations
324                  Spouses  20091  Open Eligibility Human Situations
325               Dependents  20092  Open Eligibility Human Situations
326  Intellectual Disability  20093  Open Eligibility Human Situations

[327 rows x 3 columns]

## 1.1 drop missing values based on rows.

In [34]:
df.dropna(axis=0)

                        name     id                         vocabulary
0                  Emergency   1101    Open Eligibility Human Services
1                       Food   1102    Open Eligibility Human Services
2                    Housing   1103    Open Eligibility Human Services
3                      Goods   1104    Open Eligibility Human Services
4                    Transit   1105    Open Eligibility Human Services
..                       ...    ...                                ...
322                In Danger  20089  Open Eligibility Human Situations
323          Chronic Illness  20090  Open Eligibility Human Situations
324                  Spouses  20091  Open Eligibility Human Situations
325               Dependents  20092  Open Eligibility Human Situations
326  Intellectual Disability  20093  Open Eligibility Human Situations

[327 rows x 3 columns]

# 2. fill missing values.

In [36]:
df1 = pd.read_csv("free-taxonomy.csv")

## 2.1 fill missing values based rows

In [37]:
df1.fillna("apple")

,name,id,parent_name,parent_id,vocabulary,x-description,x-notes,services
0,Emergency,1101,0,0.0,Open Eligibility Human Services,"Services for psychiatric emergencies, emergenc...",apple,apple
1,Food,1102,0,0.0,Open Eligibility Human Services,"Services for free meals, food pantries, help p...",apple,apple
2,Housing,1103,0,0.0,Open Eligibility Human Services,"Services for emergency, short-term and long-te...",apple,apple
3,Goods,1104,0,0.0,Open Eligibility Human Services,"Services for clothing, furniture, baby supplie...",apple,apple
4,Transit,1105,0,0.0,Open Eligibility Human Services,"Services for bus passes, transportation to sch...",apple,apple
...,...,...,...,...,...,...,...,...
322,In Danger,20089,Urgency,20087.0,Open Eligibility Human Situations,apple,apple,apple
323,Chronic Illness,20090,Health,1106.0,Open Eligibility Human Situations,apple,apple,apple
324,Spouses,20091,Role,20072.0,Open Eligibility Human Situations,apple,apple,apple
325,Dependents,20092,Role,20072.0,Open Eligibility Human Situations,apple,apple,apple
326,Intellectual Disability,20093,Disability,20017.0,Open Eligibility Human Situations,apple,apple,apple

## 2.2 fill missing values based on columns

In [44]:
df1["x-notes"].fillna("apple")

0      apple
1      apple
2      apple
3      apple
4      apple
       ...
322    apple
323    apple
324    apple
325    apple
326    apple
Name: x-notes, Length: 327, dtype: object

# 3. grouby()

In [45]:
customer_data = {
    "Customer_id":[101,102,103],
    "Name":["Alice","Bob","Charlie"],
    "Age":[25,29,34],
    "Total_Spend":[150.50, 45.00, 300.00],
    "Country":["USA", "CANADA", "USA"]
}
customer_data

{'Customer_id': [101, 102, 103],
 'Name': ['Alice', 'Bob', 'Charlie'],
 'Age': [25, 29, 34],
 'Total_Spend': [150.5, 45.0, 300.0],
 'Country': ['USA', 'CANADA', 'USA']}

In [46]:
type(customer_data)

dict

In [50]:
customer_data = pd.DataFrame(customer_data)
customer_data

   Customer_id     Name  Age  Total_Spend Country
0          101    Alice   25        150.5     USA
1          102      Bob   29         45.0  CANADA
2          103  Charlie   34        300.0     USA

In [51]:
type(customer_data)

pandas.core.frame.DataFrame

## 3.1 What is the total money made from each country?"

In [57]:
customer_data.groupby("Country")["Total_Spend"].sum()

Country
CANADA     45.0
USA       450.5
Name: Total_Spend, dtype: float64

In [62]:
g =customer_data.groupby("Country")

In [63]:
g.sum()

         Customer_id          Name  Age  Total_Spend
Country
CANADA           102           Bob   29         45.0
USA              204  AliceCharlie   59        450.5

## 3.2 What is the average age of customers in each country?"

In [59]:
customer_data.groupby("Country")["Age"].mean()

Country
CANADA    29.0
USA       29.5
Name: Age, dtype: float64

In [66]:
g.mean(["Age","Total_Spend"])

         Customer_id   Age  Total_Spend
Country
CANADA         102.0  29.0        45.00
USA            102.0  29.5       225.25

In [67]:
g.max()

         Customer_id     Name  Age  Total_Spend
Country
CANADA           102      Bob   29         45.0
USA              103  Charlie   34        300.0

# 4. Transpose()

In [69]:
df

                        name     id                         vocabulary
0                  Emergency   1101    Open Eligibility Human Services
1                       Food   1102    Open Eligibility Human Services
2                    Housing   1103    Open Eligibility Human Services
3                      Goods   1104    Open Eligibility Human Services
4                    Transit   1105    Open Eligibility Human Services
..                       ...    ...                                ...
322                In Danger  20089  Open Eligibility Human Situations
323          Chronic Illness  20090  Open Eligibility Human Situations
324                  Spouses  20091  Open Eligibility Human Situations
325               Dependents  20092  Open Eligibility Human Situations
326  Intellectual Disability  20093  Open Eligibility Human Situations

[327 rows x 3 columns]

In [70]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,317,318,319,320,321,322,323,324,325,326
name,Emergency,Food,Housing,Goods,Transit,Health,Money,Care,Education,Work,...,Human Trafficking Survivors,Natural Disaster Survivors,Sexual Assault Survivors,Urgency,In Crisis,In Danger,Chronic Illness,Spouses,Dependents,Intellectual Disability
id,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,...,20084,20085,20086,20087,20088,20089,20090,20091,20092,20093
vocabulary,Open Eligibility Human Services,Open Eligibility Human Services,Open Eligibility Human Services,Open Eligibility Human Services,Open Eligibility Human Services,Open Eligibility Human Services,Open Eligibility Human Services,Open Eligibility Human Services,Open Eligibility Human Services,Open Eligibility Human Services,...,Open Eligibility Human Situations,Open Eligibility Human Situations,Open Eligibility Human Situations,Open Eligibility Human Situations,Open Eligibility Human Situations,Open Eligibility Human Situations,Open Eligibility Human Situations,Open Eligibility Human Situations,Open Eligibility Human Situations,Open Eligibility Human Situations

In [71]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,317,318,319,320,321,322,323,324,325,326
name,Emergency,Food,Housing,Goods,Transit,Health,Money,Care,Education,Work,...,Human Trafficking Survivors,Natural Disaster Survivors,Sexual Assault Survivors,Urgency,In Crisis,In Danger,Chronic Illness,Spouses,Dependents,Intellectual Disability
id,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,...,20084,20085,20086,20087,20088,20089,20090,20091,20092,20093
vocabulary,Open Eligibility Human Services,Open Eligibility Human Services,Open Eligibility Human Services,Open Eligibility Human Services,Open Eligibility Human Services,Open Eligibility Human Services,Open Eligibility Human Services,Open Eligibility Human Services,Open Eligibility Human Services,Open Eligibility Human Services,...,Open Eligibility Human Situations,Open Eligibility Human Situations,Open Eligibility Human Situations,Open Eligibility Human Situations,Open Eligibility Human Situations,Open Eligibility Human Situations,Open Eligibility Human Situations,Open Eligibility Human Situations,Open Eligibility Human Situations,Open Eligibility Human Situations

# 5. Data Combining & Merging

## 5.1 Concatenate()

In [2]:
import pandas as pd

In [10]:
df1 = pd.read_csv("Titanic-Dataset.csv")
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
df2 = df1[["PassengerId","Survived","Pclass","Name"]][0:3]
df2

,PassengerId,Survived,Pclass,Name
0,1,0,3,"Braund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,3,"Heikkinen, Miss. Laina"

In [12]:
df3 = df1[["PassengerId","Survived","Pclass","Name"]][3:6]
df3

   PassengerId  Survived  Pclass                                          Name
3            4         1       1  Futrelle, Mrs. Jacques Heath (Lily May Peel)
4            5         0       3                      Allen, Mr. William Henry
5            6         0       3                              Moran, Mr. James

### 1. vertical Concate

In [16]:
pd.concat([df2,df3])

,PassengerId,Survived,Pclass,Name
0,1,0,3,"Braund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,3,"Heikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,5,0,3,"Allen, Mr. William Henry"
5,6,0,3,"Moran, Mr. James"

### 2. horizontal concat

In [17]:
pd.concat([df2,df3],axis=1)

,PassengerId,Survived,Pclass,Name,PassengerId,Survived,Pclass,Name
0,1.0,0.0,3.0,"Braund, Mr. Owen Harris",NaN,NaN,NaN,NaN
1,2.0,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",NaN,NaN,NaN,NaN
2,3.0,1.0,3.0,"Heikkinen, Miss. Laina",NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,4.0,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,NaN,NaN,NaN,NaN,5.0,0.0,3.0,"Allen, Mr. William Henry"
5,NaN,NaN,NaN,NaN,6.0,0.0,3.0,"Moran, Mr. James"